language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SYMFONY_VERSION=4.0.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; else composer require "symfony/symfony:dev-master"; fi;

install:
  - composer update --dev --prefer-source $COMPOSER_FLAGS

script: phpunit

notifications:
  email:
    - travis-ci@composieux.fr
