language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.6.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - if [ "$SYMFONY_VERSION" = "2.8.*@dev" ] || [ "$SYMFONY_VERSION" = "3.0.*@dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source

script: phpunit

notifications:
  email:
    - vincent.composieux@gmail.com

