language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION=2.5.*
    - php: 7.2
      env: SYMFONY_VERSION=2.7.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.0.*
    - php: 7.2
      env: SYMFONY_VERSION=3.1.*
    - php: 7.2
      env: SYMFONY_VERSION=3.2.*
  allow_failures:
    - php: hhvm

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; else composer require "symfony/symfony:dev-master"; fi;
  - if [ "$SYMFONY_VERSION" = "3.1.*@dev" ] || [ "$SYMFONY_VERSION" = "3.2.*@dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - composer update --dev --prefer-source $COMPOSER_FLAGS

script: phpunit

notifications:
  email:
    - travis-ci@composieux.fr
